### ISSUE TITLE
Add a liveness probe to the API server

### ISSUE THREAD

**Issue by droslean** [vega-project/ccb-operator#95]
Since we are running the API server in a container, we need to expose a `/healthz` endpoint to allow a liveness probe. Kubelet needs to know when to restart the container and this is the most common k8s way to do it.

Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

@odvarkadaniel

**Comment by odvarkadaniel** [comment]
Do I need to create the image files as well? Should it work like in the example in the link or different?
For example: check the endpoint every X sec?

**Comment by droslean** [comment]
You only need to create a new endpoint `/healthz` to response in a 200 statuscode and then add the liveness prove in the deployment file.
