### ISSUE TITLE
Write unittests for all of the server operations in API server

### ISSUE THREAD

**Issue by droslean** [vega-project/ccb-operator#97]
@odvarkadaniel

**Comment by odvarkadaniel** [comment]
Hi, do I need to use the dry run simulators etc. in order to test the server operations?

**Comment by droslean** [comment]
No, the dry run simulator has nothing to do with those unittests. You will need a fake client though, like the one we use when dry-run.

**Comment by odvarkadaniel** [comment]
The answer from the api server is so long and detailed, could you please tell me, if there is a function or something to trim/access it?

I get this: 
"metadata":{},"items":[{"kind":"Calculation","apiVersion":"vega.io/v1","metadata":{"name":"calc-xc864fxvd5xccn6x","creationTimestamp":null},"spec":{"steps":[{"command":"atlas12_ada","args":["s"]},{"command":"atlas12_ada","args":["r"]},{"command":"synspec49","args":["\u003c","input_tlusty_fortfive"]}],"teff":10000,"logG":4},"dbkey":"vz.star:teff_10000","assign":"","status":{"startTime":"2021-03-22T12:54:55Z"},"phase":"Created"}]}

But I would like to work only with teff, logG and DBkey values. Thank you

**Comment by odvarkadaniel** [comment]
Also, could you please give me an example of what this variable could be(id)?
https://github.com/vega-project/ccb-operator/blob/6dc9ba9eea18543e279861c7b2b3b7f225b16ceb/cmd/apiserver/server.go#L71

**Comment by droslean** [comment]
In your tests, just make sure that you create some calculations with the fake client, and there is no need to add steps in them. The calculation name with teff and logG would be enough. That `id` is the calculation name. This is a variable from the mux. see [here](https://github.com/vega-project/ccb-operator/blob/6dc9ba9eea18543e279861c7b2b3b7f225b16ceb/cmd/apiserver/main.go#L238)
